### ISSUE TITLE
questions about run_test_pred.sh output

### ISSUE THREAD

**Issue by michaelanekson** [ncbi/BioREx#10]
I use run_test_pred_sh to predict my input data which has been transformed into BioRED format. In the run_test_pred.sh script, there are two outputs: out_tsv_file and out_pubtator_files. When I run the run_test_pred_sh, the prediction is successfully added in the out_pubtator_files but why does the "out_tsv_file" result is still none? 
You can see the result in that zip file. The "out_pubtator_files" file has prediction results but the out_tsv_file has "None". Is this normal? 
I also provide my input data as well in that attached file.
[10_sentences_sample.zip](https://github.com/user-attachments/files/16290312/10_sentences_sample.zip)

Note:
I have tried using the input example from BioRED file that you gave to me and the out_tsv_file result is still "None".

**Comment by ptlai** [comment]
Hi @michaelanekson ,

out_tsv_file is a temporary file created by converting the input PubTator file into a TSV file for prediction. If the input PubTator file doesn't have relation annotations, the label column in the prediction output will be 'None'.

Best,
Po-Ting

**Comment by michaelanekson** [comment]
Ok, got it. I understand. Thank you for your help and patience. I will close this issue then.

Michael
