### ISSUE TITLE
documentation for BioREx datasets

### ISSUE THREAD

**Issue by RLWOHIO** [ncbi/BioREx#15]
I am trying to make sense of the file format in https://ftp.ncbi.nlm.nih.gov/pub/lu/BioREx/datasets.zip. Is there any documentation explaining the various fields and how these files are generated? For example,  datasets\ncbi_relation\processed\train.tsv appears to be the input and gets converted to datasets\biorex\processed\train.tsv. Now, where does the input, datasets\ncbi_relation\processed\train.tsv, come from and how? And what are some of these fields below?

10491763	GeneOrGeneProduct	GeneOrGeneProduct	6927	rs74805019	True	0	What is [Litcoin] between ...

the first field seems to be pubmed ID. Why are the field 2 and 3 duplicated? What are the field 4, 5, 6, 7? Is the field 8 the output of AIONER package?
Thanks!

**Comment by ptlai** [comment]
Hi @RLWOHIO,  

Thank you for your interest in our work!  

The datasets are generated using the script available at [build_biorex_datasets.sh](https://github.com/ncbi/BioREx/blob/main/scripts/build_biorex_datasets.sh). Below is an overview of the main steps involved:  

1. **Converting `.pubtator` Files to `.tsv` Files**  
   - Lines 3–30 of `build_biorex_datasets.sh` handle this conversion.  
   - Line 33 is specific to certain experiments and can be skipped if not required.  

2. **Normalization Rules Setup for Different Datasets**  
   - Lines 37–74 define four types of normalization rules:  
     
     - **`norm_rel_**` Rule:**  
       - Consists of four elements: `NE type 1 | NE type 2 | Source Relation Label | Target Relation Label`.  
       - If "Source Relation Label" is `"*"`, it includes all relation labels except those containing `"None"` (e.g., `"None-DISGENET"`).  
       - This rule converts lines in the `.tsv` file where the `Source Relation Label` matches the rule into the `Target Relation Label`.  
       
     - **`norm_pair_**` Rule:**  
       - Consists of four elements: `Source NE type 1 | Source NE type 2 | Target NE type 1 | Target NE type 2`.  
       - Converts lines in the `.tsv` file with matching `Source NE types` into the `Target NE types`.  

     - **`normalize_tag_2_tag` Rule:**  
       - Converts special tokens from the source dataset into specific tokens for the target dataset.  
       - Example: `"[DISGENET]|[Litcoin];[EMU_BC]|[Litcoin];[EMU_PC]|[Litcoin];[PHARMGKB]|[Litcoin]"` converts the special tokens `[DISGENET]`, `[EMU_BC]`, `[EMU_PC]`, and `[PHARMGKB]` in the `.tsv` file into `[Litcoin]`.  

     - **`in_****_train` Rule:**  
       - Removes lines in the `.tsv` file with relation labels ending in `"|None-***"`.  

3. **Applying Rule Combinations to Generate Datasets**  
   - Lines 91–159 specify the source and target datasets and apply the appropriate normalization rules.  

Below are the meanings of each column in the `.tsv` files:  
1. **PMID**  
2. **NE type 1**  
3. **NE type 2**  
4. **ID 1**  
5. **ID 2**  
6. **In Same Paragraph:** Not used  
7. **Distance Between Paragraphs:** Not used  
8. **Input Text for BERT**  
9. **Reserved:** Not used  
10. **Label**  

Please feel free to reach out if you need further clarification.

**Comment by ptlai** [comment]
Hi @RLWOHIO,

Your understanding is almost correct! Both script 1 and script 2 are located in the following file https://github.com/ncbi/BioREx/blob/main/scripts/build_biorex_datasets.sh. 

- Script 1 can be found on lines 3–4:

```
python src/dataset_format_converter/convert_pubtator_2_tsv.py \
    --exp_option biored
```

- Script 2 is located on lines 91–101:

```
python src/dataset_format_converter/convert_pubtator_2_tsv.py \
  --exp_option combine_sets \
  --in_main_train_files "${in_biored_train}" \
  --in_main_test_files "${in_biored_test}" \
  --in_other_train_files "${in_aimed_train};${in_cdr_train};${in_ddi_train};${in_disgenet_train};${in_drugprot_train};${in_emu_train};${in_hprd50_train};${in_pharmgkb_train}" \
  --in_other_test_files "" \
  --out_train_tsv_file "${out_biorex_train}" \
  --out_test_tsv_file "${out_biorex_test}" \
  --normalize_pair_2_rel_type "${normalize_pair_2_rel_type}" \
  --normalize_pair_2_pair "${normalize_pair_2_pair}" \
  --normalize_tag_2_tag "${normalize_tag_2_tag}"
```

**Comment by ptlai** [comment]
Great! Thanks.
